MotorWare f2802x Module API Documentation: PARK
PARK
Modules
Module overview
Data Structures
struct _PARK_Obj_
Defines the PARK object.
Typedefs
typedef struct _PARK_Obj_ PARK_Obj
Defines the PARK object.
typedef struct _PARK_Obj_ * PARK_Handle
Defines the PARK handle.
typedef struct _PARK_Obj_ PARK_Obj
Defines the PARK object.
typedef struct _PARK_Obj_ * PARK_Handle
Defines the PARK handle.
Functions
static _iq PARK_getCosTh (PARK_Handle handle)
Gets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
static void PARK_getPhasor (PARK_Handle handle, MATH_vec2 *pPhasor)
Gets the cosine/sine phasor for the Park transform.
static _iq PARK_getSinTh (PARK_Handle handle)
Gets the sine of the angle between the d,q and the alpha,beta coordinate systems.
PARK_Handle PARK_init (void *pMemory, const size_t numBytes)
Initializes the Park transform module.
static void PARK_run (PARK_Handle handle, const MATH_vec2 *pInVec, MATH_vec2 *pOutVec)
Runs the Park transform module.
static void PARK_setCosTh (PARK_Handle handle, const _iq cosTh)
Sets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
static void PARK_setPhasor (PARK_Handle handle, const MATH_vec2 *pPhasor)
Sets the cosine/sine phasor for the inverse Park transform.
static void PARK_setSinTh (PARK_Handle handle, const _iq sinTh)
Sets the sine of the angle between the d,q and the alpha,beta coordinate systems.
static void PARK_setup (PARK_Handle handle, const _iq angle_pu)
Sets up the Park transform module.
static void PARK_setCosTh (PARK_Handle handle, const float_t cosTh)
Sets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
static void PARK_setSinTh (PARK_Handle handle, const float_t sinTh)
Sets the sine of the angle between the d,q and the alpha,beta coordinate systems.
static void PARK_setup (PARK_Handle handle, const float_t Th)
Sets up the Park transform module.
Detailed Description
Data Structure Documentation
struct _PARK_Obj_
Defines the PARK object.
Definition at line 73 of file 32b/park.h.
Data Fields
_iq cosTh the cosine of the angle between the d,q and the alpha,beta coordinate systems
float_t cosTh the cosine of the angle between the d,q and the alpha,beta coordinate systems
_iq sinTh the sine of the angle between the d,q and the alpha,beta coordinate systems
float_t sinTh the sine of the angle between the d,q and the alpha,beta coordinate systems
Typedef Documentation
typedef struct _PARK_Obj_* PARK_Handle
Defines the PARK handle.
Definition at line 84 of file 32b/park.h.
typedef struct _PARK_Obj_* PARK_Handle
Defines the PARK handle.
Definition at line 87 of file float/park.h.
typedef struct _PARK_Obj_ PARK_Obj
Defines the PARK object.
typedef struct _PARK_Obj_ PARK_Obj
Defines the PARK object.
Function Documentation
static _iq PARK_getCosTh (PARK_Handle handle) inline static
Gets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
Returns
The cosine of the angle
Definition at line 93 of file 32b/park.h.
References _PARK_Obj_::cosTh.
static void PARK_getPhasor (PARK_Handle handle, MATH_vec2 * pPhasor) inline static
Gets the cosine/sine phasor for the Park transform.
Parameters
[in] handle The Park transform handle
[in] pPhasor The pointer to the cosine/sine phasor
Definition at line 104 of file 32b/park.h.
References _PARK_Obj_::cosTh, _PARK_Obj_::sinTh, and _MATH_vec2_::value.
static _iq PARK_getSinTh (PARK_Handle handle) inline static
Gets the sine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
Returns
The sine of the angle
Definition at line 118 of file 32b/park.h.
References _PARK_Obj_::sinTh.
PARK_Handle PARK_init (void * pMemory, const size_t numBytes)
Initializes the Park transform module.
Parameters
[in] pMemory A pointer to the memory for the Park object
[in] numBytes The number of bytes allocated for the Park object, bytes
Returns
The Park (PARK) object handle
Definition at line 55 of file 32b/park.c.
static void PARK_run (PARK_Handle handle, const MATH_vec2 * pInVec, MATH_vec2 * pOutVec) inline static
Runs the Park transform module.
Parameters
[in] handle The Park transform handle
[in] pInVec The pointer to the input vector
[in] pOutVec The pointer to the output vector
Definition at line 137 of file 32b/park.h.
References _IQmpy, _PARK_Obj_::cosTh, _PARK_Obj_::sinTh, and _MATH_vec2_::value.
Referenced by CTRL_runOnLine(), and CTRL_runOnLine_User().
static void PARK_setCosTh (PARK_Handle handle, const _iq cosTh) inline static
Sets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
[in] cosTh The cosine of the angle
Definition at line 158 of file 32b/park.h.
References _PARK_Obj_::cosTh.
static void PARK_setCosTh (PARK_Handle handle, const float_t cosTh) inline static
Sets the cosine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
[in] cosTh The cosine of the angle
Definition at line 163 of file float/park.h.
References _PARK_Obj_::cosTh.
static void PARK_setPhasor (PARK_Handle handle, const MATH_vec2 * pPhasor) inline static
Sets the cosine/sine phasor for the inverse Park transform.
Parameters
[in] handle The Park transform handle
[in] pPhasor The pointer to the cosine/sine phasor, pu
Definition at line 171 of file 32b/park.h.
References _PARK_Obj_::cosTh, _PARK_Obj_::sinTh, and _MATH_vec2_::value.
Referenced by CTRL_runOnLine(), and CTRL_runOnLine_User().
static void PARK_setSinTh (PARK_Handle handle, const _iq sinTh) inline static
Sets the sine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
[in] sinTh The sine of the angle
Definition at line 185 of file 32b/park.h.
References _PARK_Obj_::sinTh.
static void PARK_setSinTh (PARK_Handle handle, const float_t sinTh) inline static
Sets the sine of the angle between the d,q and the alpha,beta coordinate systems.
Parameters
[in] handle The Park transform handle
[in] sinTh The sine of the angle
Definition at line 190 of file float/park.h.
References _PARK_Obj_::sinTh.
static void PARK_setup (PARK_Handle handle, const _iq angle_pu) inline static
Sets up the Park transform module.
Parameters
[in] handle The Park transform handle
[in] angle_pu The angle between the d,q and the alpha,beta coordinate systems, pu
Definition at line 198 of file 32b/park.h.
References _IQcosPU, _IQsinPU, _PARK_Obj_::cosTh, and _PARK_Obj_::sinTh.
static void PARK_setup (PARK_Handle handle, const float_t Th) inline static
Sets up the Park transform module.
Parameters
[in] handle The Park transform handle
[in] Th The angle between the d,q and the alpha,beta coordinate systems, rad
Definition at line 206 of file float/park.h.
References _PARK_Obj_::cosTh, and _PARK_Obj_::sinTh.