MotorWare f2805x Module API Documentation: HAL
HAL
Macros
#define Device_cal (void (*)(void))0x3D7C80
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
#define getOsc1FineTrimSlope() (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
#define getOsc1FineTrimOffset() (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
#define getOsc1CoarseTrim() (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
#define getOsc2FineTrimSlope() (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
#define getOsc2FineTrimOffset() (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
#define getOsc2CoarseTrim() (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
#define getRefTempOffset() (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
#define HAL_PWM_DBFED_CNT 1
Defines the PWM deadband falling edge delay count (system clocks)
#define HAL_PWM_DBRED_CNT 1
Defines the PWM deadband rising edge delay count (system clocks)
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
#define Device_cal (void (*)(void))0x3D7C80
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
#define getOsc1FineTrimSlope() (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
#define getOsc1FineTrimOffset() (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
#define getOsc1CoarseTrim() (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
#define getOsc2FineTrimSlope() (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
#define getOsc2FineTrimOffset() (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
#define getOsc2CoarseTrim() (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
#define getRefTempOffset() (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
#define HAL_PWM_DBFED_CNT 1
Defines the PWM deadband falling edge delay count (system clocks)
#define HAL_PWM_DBRED_CNT 1
Defines the PWM deadband rising edge delay count (system clocks)
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
#define Device_cal (void (*)(void))0x3D7C80
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
#define getOsc1FineTrimSlope() (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
#define getOsc1FineTrimOffset() (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
#define getOsc1CoarseTrim() (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
#define getOsc2FineTrimSlope() (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
#define getOsc2FineTrimOffset() (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
#define getOsc2CoarseTrim() (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
#define getRefTempOffset() (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
#define HAL_PWM_DBFED_CNT (uint16_t)(2.0 * (float_t)USER_SYSTEM_FREQ_MHz)
Defines the PWM deadband falling edge delay count (system clocks)
#define HAL_PWM_DBRED_CNT (uint16_t)(2.0 * (float_t)USER_SYSTEM_FREQ_MHz)
Defines the PWM deadband rising edge delay count (system clocks)
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
Enumerations
enum HAL_QepSelect_e {
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1, HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1,
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1
}
Enumeration for the QEP setup.
enum HAL_LedNumber_e {
HAL_Gpio_LED2 =GPIO_Number_31, HAL_Gpio_LED3 =GPIO_Number_34, HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34,
HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34
}
Enumeration for the LED numbers.
enum HAL_SensorType_e {
HAL_SensorType_Current =0, HAL_SensorType_Voltage, HAL_SensorType_Current =0, HAL_SensorType_Voltage,
HAL_SensorType_Current =0, HAL_SensorType_Voltage
}
Enumeration for the sensor types.
enum HAL_QepSelect_e {
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1, HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1,
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1
}
Enumeration for the QEP setup.
enum HAL_LedNumber_e {
HAL_Gpio_LED2 =GPIO_Number_31, HAL_Gpio_LED3 =GPIO_Number_34, HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34,
HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34
}
enum HAL_SensorType_e {
HAL_SensorType_Current =0, HAL_SensorType_Voltage, HAL_SensorType_Current =0, HAL_SensorType_Voltage,
HAL_SensorType_Current =0, HAL_SensorType_Voltage
}
enum HAL_QepSelect_e {
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1, HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1,
HAL_Qep_QEP1 =0, HAL_Qep_QEP2 =1
}
Enumeration for the QEP setup.
enum HAL_LedNumber_e {
HAL_Gpio_LED2 =GPIO_Number_31, HAL_Gpio_LED3 =GPIO_Number_34, HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34,
HAL_Gpio_LED1 =GPIO_Number_31, HAL_Gpio_LED2 =GPIO_Number_34
}
Enumeration for the LED numbers.
enum HAL_SensorType_e {
HAL_SensorType_Current =0, HAL_SensorType_Voltage, HAL_SensorType_Current =0, HAL_SensorType_Voltage,
HAL_SensorType_Current =0, HAL_SensorType_Voltage
}
Enumeration for the sensor types.
Functions
interrupt void mainISR (void)
static void HAL_acqAdcInt (HAL_Handle handle, const ADC_IntNumber_e intNumber)
Acknowledges an interrupt from the ADC so that another ADC interrupt can happen again.
static void HAL_acqPwmInt (HAL_Handle handle, const PWM_Number_e pwmNumber)
Acknowledges an interrupt from the PWM so that another PWM interrupt can happen again.
void HAL_cal (HAL_Handle handle)
Executes calibration routines.
void HAL_disableGlobalInts (HAL_Handle handle)
Disables global interrupts.
void HAL_disableWdog (HAL_Handle handle)
Disables the watch dog.
static void HAL_disablePwm (HAL_Handle handle)
Disables the PWM device.
void HAL_enableAdcInts (HAL_Handle handle)
Enables the ADC interrupts.
void HAL_enableDebugInt (HAL_Handle handle)
Enables the debug interrupt.
void HAL_enableGlobalInts (HAL_Handle handle)
Enables global interrupts.
static void HAL_enablePwm (HAL_Handle handle)
Enables the PWM devices.
void HAL_enablePwmInt (HAL_Handle handle)
Enables the PWM interrupt.
static ADC_SocSampleDelay_e HAL_getAdcSocSampleDelay (HAL_Handle handle, const ADC_SocNumber_e socNumber)
Gets the ADC delay value.
static _iq HAL_getBias (HAL_Handle handle, const HAL_SensorType_e sensorType, uint_least8_t sensorNumber)
Gets the ADC bias value.
static _iq HAL_getCurrentScaleFactor (HAL_Handle handle)
Gets the current scale factor.
static uint_least8_t HAL_getNumCurrentSensors (HAL_Handle handle)
Gets the number of current sensors.
static uint_least8_t HAL_getNumVoltageSensors (HAL_Handle handle)
Gets the number of voltage sensors.
static _iq HAL_getOffsetBeta_lp_pu (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber)
Gets the value used to set the low pass filter pole for offset estimation.
static _iq HAL_getOffsetValue (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber)
Gets the offset value.
static _iq HAL_getVoltageScaleFactor (HAL_Handle handle)
Gets the voltage scale factor.
void HAL_setupFaults (HAL_Handle handle)
Configures the fault protection logic.
HAL_Handle HAL_init (void *pMemory, const size_t numBytes)
Initializes the hardware abstraction layer (HAL) object.
static void HAL_initIntVectorTable (HAL_Handle handle)
Initializes the interrupt vector table.
static void HAL_readAdcData (HAL_Handle handle, HAL_AdcData_t *pAdcData)
Reads the ADC data.
static void HAL_readAdcDataWithOffsets (HAL_Handle handle, HAL_AdcData_t *pAdcData)
Reads the ADC data.
static uint32_t HAL_readTimerCnt (HAL_Handle handle, const uint_least8_t timerNumber)
Reads the timer count.
static void HAL_reloadTimer (HAL_Handle handle, const uint_least8_t timerNumber)
Reloads the timer.
static void HAL_startTimer (HAL_Handle handle, const uint_least8_t timerNumber)
Starts the timer.
static void HAL_stopTimer (HAL_Handle handle, const uint_least8_t timerNumber)
Stops the timer.
static void HAL_setTimerPeriod (HAL_Handle handle, const uint_least8_t timerNumber, const uint32_t period)
Sets the timer period.
static uint32_t HAL_getTimerPeriod (HAL_Handle handle, const uint_least8_t timerNumber)
Gets the timer period.
static void HAL_setAdcSocSampleDelay (HAL_Handle handle, const ADC_SocNumber_e socNumber, const ADC_SocSampleDelay_e sampleDelay)
Sets the ADC SOC sample delay value.
static void HAL_setBias (HAL_Handle handle, const HAL_SensorType_e sensorType, uint_least8_t sensorNumber, const _iq bias)
Sets the ADC bias value.
static void HAL_setGpioHigh (HAL_Handle handle, const GPIO_Number_e gpioNumber)
Sets the GPIO pin high.
static void HAL_toggleGpio (HAL_Handle handle, const GPIO_Number_e gpioNumber)
Toggles the GPIO pin.
static void HAL_setGpioLow (HAL_Handle handle, const GPIO_Number_e gpioNumber)
Sets the GPIO pin low.
static void HAL_setCurrentScaleFactor (HAL_Handle handle, const _iq current_sf)
Sets the current scale factor in the hardware abstraction layer.
static void HAL_setNumCurrentSensors (HAL_Handle handle, const uint_least8_t numCurrentSensors)
Sets the number of current sensors.
static void HAL_setNumVoltageSensors (HAL_Handle handle, const uint_least8_t numVoltageSensors)
Sets the number of voltage sensors.
static void HAL_setOffsetBeta_lp_pu (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq beta_lp_pu)
Sets the value used to set the low pass filter pole for offset estimation.
static void HAL_setOffsetInitCond (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq initCond)
Sets the offset initial condition value for offset estimation.
static void HAL_setOffsetValue (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq value)
Sets the initial offset value for offset estimation.
static void HAL_setVoltageScaleFactor (HAL_Handle handle, const _iq voltage_sf)
Sets the voltage scale factor in the hardware abstraction layer.
void HAL_setParams (HAL_Handle handle, const USER_Params *pUserParams)
Sets the hardware abstraction layer parameters.
void HAL_setupAdcs (HAL_Handle handle)
Sets up the ADCs (Analog to Digital Converters)
void HAL_setupAfe (HAL_Handle halHandle)
Sets up the AFE (Analog Front End)
void HAL_setupClks (HAL_Handle handle)
Sets up the clocks.
void HAL_setupFlash (HAL_Handle handle)
Sets up the FLASH.
void HAL_setupGpios (HAL_Handle handle)
Sets up the GPIO (General Purpose I/O) pins.
void HAL_setupPeripheralClks (HAL_Handle handle)
Sets up the peripheral clocks.
void HAL_setupPie (HAL_Handle handle)
Sets up the PIE (Peripheral Interrupt Expansion)
void HAL_setupPll (HAL_Handle handle, const PLL_ClkFreq_e clkFreq)
Sets up the PLL (Phase Lock Loop)
void HAL_setupPwms (HAL_Handle handle, const float_t systemFreq_MHz, const float_t pwmPeriod_usec, const uint_least16_t numPwmTicksPerIsrTick)
Sets up the PWMs (Pulse Width Modulators)
void HAL_setupPwmDacs (HAL_Handle handle)
Sets up the PWM DACs (Pulse Width Modulator Digital to Analof Converters)
void HAL_setupTimers (HAL_Handle handle, const float_t systemFreq_MHz)
Sets up the timers.
void HAL_setupQEP (HAL_Handle handle, HAL_QepSelect_e qep)
Sets up the QEP peripheral.
static void HAL_updateAdcBias (HAL_Handle handle)
Updates the ADC bias values.
static void HAL_writeDacData (HAL_Handle handle, HAL_DacData_t *pDacData)
Writes DAC data to the PWM comparators for DAC (digital-to-analog conversion) output.
static void HAL_writePwmData (HAL_Handle handle, HAL_PwmData_t *pPwmData)
Writes PWM data to the PWM comparators for motor control.
static uint16_t HAL_readPwmCmpA (HAL_Handle handle, const PWM_Number_e pwmNumber)
Reads PWM compare register A.
static uint16_t HAL_readPwmCmpAM (HAL_Handle handle, const PWM_Number_e pwmNumber)
Reads PWM compare mirror register A.
static uint16_t HAL_readPwmCmpB (HAL_Handle handle, const PWM_Number_e pwmNumber)
Reads PWM compare register B.
static void HAL_setTrigger (HAL_Handle handle, const SVGENCURRENT_IgnoreShunt_e ignoreShunt, const int16_t minwidth, const int16_t cmpOffset)
static uint16_t HAL_readPwmPeriod (HAL_Handle handle, const PWM_Number_e pwmNumber)
Reads PWM period register.
void HAL_AdcCalChanSelect (HAL_Handle handle, const ADC_SocChanNumber_e chanNumber)
Selects the analog channel used for calibration.
uint16_t HAL_AdcCalConversion (HAL_Handle handle)
Reads the converted value from the selected calibration channel.
void HAL_AdcOffsetSelfCal (HAL_Handle handle)
Executes the offset calibration of the ADC.
uint16_t HAL_getOscTrimValue (int16_t coarse, int16_t fine)
Converts coarse and fine oscillator trim values into a single 16bit word value.
void HAL_OscTempComp (HAL_Handle handle)
Executes the oscillator 1 and 2 calibration functions.
void HAL_osc1Comp (HAL_Handle handle, const int16_t sensorSample)
Executes the oscillator 1 calibration based on input sample.
void HAL_osc2Comp (HAL_Handle handle, const int16_t sensorSample)
Executes the oscillator 2 calibration based on input sample.
Detailed Description
Macro Definition Documentation
#define Device_cal (void (*)(void))0x3D7C80
Definition at line 69 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
#define Device_cal (void (*)(void))0x3D7C80
Definition at line 69 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define Device_cal (void (*)(void))0x3D7C80
Definition at line 69 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
Definition at line 76 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
Definition at line 76 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define FP_ROUND FP_SCALE/2
Defines the quantity added to Q15 numbers before converting to integer to round the number.
Definition at line 76 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
Defines the scale factor for Q15 fixed point numbers (2^15)
Definition at line 73 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
Defines the scale factor for Q15 fixed point numbers (2^15)
Definition at line 73 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define FP_SCALE 32768
Defines used in oscillator calibration functions.
Defines the scale factor for Q15 fixed point numbers (2^15)
Definition at line 73 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc1CoarseTrim () (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
Definition at line 93 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp().
#define getOsc1CoarseTrim () (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
Definition at line 93 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc1CoarseTrim () (*(int16_t (*)(void))0x3D7E46)()
Defines the oscillator 1 coarse trim.
Definition at line 93 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getOsc1FineTrimOffset () (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
Definition at line 90 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc1FineTrimOffset () (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
Definition at line 90 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getOsc1FineTrimOffset () (*(int16_t (*)(void))0x3D7E43)()
Defines the oscillator 1 fine trim at high temp.
Definition at line 90 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp().
#define getOsc1FineTrimSlope () (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
Defines the slope used to compensate oscillator 1 (fine trim steps / ADC code). Stored in fixed point Q15 format
Definition at line 87 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc1FineTrimSlope () (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
Defines the slope used to compensate oscillator 1 (fine trim steps / ADC code). Stored in fixed point Q15 format
Definition at line 87 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getOsc1FineTrimSlope () (*(int16_t (*)(void))0x3D7E40)()
The following functions return reference values stored in OTP.
Defines the slope used to compensate oscillator 1 (fine trim steps / ADC code). Stored in fixed point Q15 format
Definition at line 87 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp().
#define getOsc2CoarseTrim () (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
Definition at line 103 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc2Comp().
#define getOsc2CoarseTrim () (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
Definition at line 103 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc2CoarseTrim () (*(int16_t (*)(void))0x3D7E4F)()
Defines the oscillator 2 coarse trim.
Definition at line 103 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getOsc2FineTrimOffset () (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
Definition at line 100 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc2FineTrimOffset () (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
Definition at line 100 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc2Comp().
#define getOsc2FineTrimOffset () (*(int16_t (*)(void))0x3D7E4C)()
Defines the oscillator 2 fine trim at high temp.
Definition at line 100 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getOsc2FineTrimSlope () (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
in fixed point Q15 format.
Definition at line 97 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc2Comp().
#define getOsc2FineTrimSlope () (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
in fixed point Q15 format.
Definition at line 97 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getOsc2FineTrimSlope () (*(int16_t (*)(void))0x3D7E49)()
Defines the slope used to compensate oscillator 2 (fine trim steps / ADC code). Stored.
in fixed point Q15 format.
Definition at line 97 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define getRefTempOffset () (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
Definition at line 106 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define getRefTempOffset () (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
Definition at line 106 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
#define getRefTempOffset () (*(int16_t (*)(void))0x3D7E52)()
Defines the ADC reading of temperature sensor at reference temperature for compensation.
Definition at line 106 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_PWM_DBFED_CNT (uint16_t)(2.0 * (float_t)USER_SYSTEM_FREQ_MHz)
Defines the PWM deadband falling edge delay count (system clocks)
Definition at line 110 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define HAL_PWM_DBFED_CNT 1
Defines the PWM deadband falling edge delay count (system clocks)
Definition at line 110 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_setupPwms().
#define HAL_PWM_DBFED_CNT 1
Defines the PWM deadband falling edge delay count (system clocks)
Definition at line 110 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_PWM_DBRED_CNT (uint16_t)(2.0 * (float_t)USER_SYSTEM_FREQ_MHz)
Defines the PWM deadband rising edge delay count (system clocks)
Definition at line 115 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define HAL_PWM_DBRED_CNT 1
Defines the PWM deadband rising edge delay count (system clocks)
Definition at line 115 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_PWM_DBRED_CNT 1
Defines the PWM deadband rising edge delay count (system clocks)
Definition at line 115 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_setupPwms().
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
Definition at line 130 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
Definition at line 130 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_toggleLed HAL_toggleGpio
Defines the function to turn LEDs on.
Definition at line 130 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
Definition at line 120 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
Definition at line 120 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
#define HAL_turnLedOff HAL_setGpioLow
Defines the function to turn LEDs off.
Definition at line 120 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
Definition at line 125 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
Definition at line 125 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
#define HAL_turnLedOn HAL_setGpioHigh
Defines the function to turn LEDs on.
Definition at line 125 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
(-31 to 31) to (1 to 63). This guarantees that the trim is positive and can therefore be efficiently rounded
Definition at line 81 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
(-31 to 31) to (1 to 63). This guarantees that the trim is positive and can therefore be efficiently rounded
Definition at line 81 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
#define OSC_POSTRIM 32
Defines the amount to add to Q16.15 fixed point number to shift from a fine trim range of.
(-31 to 31) to (1 to 63). This guarantees that the trim is positive and can therefore be efficiently rounded
Definition at line 81 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
Definition at line 82 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
Definition at line 82 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
#define OSC_POSTRIM_OFF FP_SCALE*OSC_POSTRIM
Definition at line 82 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
Enumeration Type Documentation
enum HAL_LedNumber_e
Enumerator
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED3
GPIO pin number for ControlCARD LED 3.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 1.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 3.
Definition at line 145 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
enum HAL_LedNumber_e
Enumeration for the LED numbers.
Enumerator
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED3
GPIO pin number for ControlCARD LED 3.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 1.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 3.
Definition at line 147 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
enum HAL_LedNumber_e
Enumeration for the LED numbers.
Enumerator
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED3
GPIO pin number for ControlCARD LED 3.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 1.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED1
GPIO pin number for ControlCARD LED 2.
HAL_Gpio_LED2
GPIO pin number for ControlCARD LED 3.
Definition at line 147 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
enum HAL_QepSelect_e
Enumeration for the QEP setup.
Enumerator
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
Definition at line 138 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
enum HAL_QepSelect_e
Enumeration for the QEP setup.
Enumerator
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
Definition at line 138 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
enum HAL_QepSelect_e
Enumeration for the QEP setup.
Enumerator
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
HAL_Qep_QEP1
Select QEP1.
HAL_Qep_QEP2
Select QEP2.
Definition at line 138 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
enum HAL_SensorType_e
Enumerator
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
Definition at line 152 of file drv8312kit_revD/f28x/f2805x/src/hal.h.
enum HAL_SensorType_e
Enumeration for the sensor types.
Enumerator
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
Definition at line 156 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
enum HAL_SensorType_e
Enumeration for the sensor types.
Enumerator
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
HAL_SensorType_Current
Enumeration for current sensor.
HAL_SensorType_Voltage
Enumeration for voltage sensor.
Definition at line 156 of file hvkit_rev1p1/f28x/f2805x/src/hal.h.
Function Documentation
static void HAL_acqAdcInt (HAL_Handle handle, const ADC_IntNumber_e intNumber) inline static
Acknowledges an interrupt from the ADC so that another ADC interrupt can happen again.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] intNumber The interrupt number
Definition at line 177 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::adcHandle, and _HAL_Obj_::pieHandle.
static void HAL_acqPwmInt (HAL_Handle handle, const PWM_Number_e pwmNumber) inline static
Acknowledges an interrupt from the PWM so that another PWM interrupt can happen again.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pwmNumber The PWM number
Definition at line 197 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pieHandle, and _HAL_Obj_::pwmHandle.
void HAL_AdcCalChanSelect (HAL_Handle handle, const ADC_SocChanNumber_e chanNumber)
Selects the analog channel used for calibration.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] chanNumber The channel number
Definition at line 291 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle.
Referenced by HAL_AdcOffsetSelfCal().
uint16_t HAL_AdcCalConversion (HAL_Handle handle)
Reads the converted value from the selected calibration channel.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Returns
The converted value
Definition at line 316 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle, and usDelay().
Referenced by HAL_AdcOffsetSelfCal().
void HAL_AdcOffsetSelfCal (HAL_Handle handle)
Executes the offset calibration of the ADC.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 246 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle, HAL_AdcCalChanSelect(), and HAL_AdcCalConversion().
Referenced by HAL_cal().
void HAL_cal (HAL_Handle handle)
Executes calibration routines.
Values for offset and gain are programmed into OTP memory at the TI factory. This calls and internal function that programs these offsets and gains into the ADC registers.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 67 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::clkHandle, HAL_AdcOffsetSelfCal(), and HAL_OscTempComp().
Referenced by HAL_setParams().
void HAL_disableGlobalInts (HAL_Handle handle)
Disables global interrupts.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 464 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::cpuHandle.
static void HAL_disablePwm (HAL_Handle handle) inline static
Disables the PWM device.
Turns off the outputs of the EPWM peripherals which will put the power switches into a high impedance state.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 239 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
void HAL_disableWdog (HAL_Handle handle)
Disables the watch dog.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 452 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::wdogHandle.
Referenced by HAL_init().
void HAL_enableAdcInts (HAL_Handle handle)
Enables the ADC interrupts.
Enables the ADC interrupt in the PIE, and CPU. Enables the interrupt to be sent from the ADC peripheral.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 475 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle, _HAL_Obj_::cpuHandle, and _HAL_Obj_::pieHandle.
void HAL_enableDebugInt (HAL_Handle handle)
Enables the debug interrupt.
The debug interrupt is used for the real-time debugger. It is not needed if the real-time debugger is not used. Clears bit 1 of ST1.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 495 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::cpuHandle.
void HAL_enableGlobalInts (HAL_Handle handle)
Enables global interrupts.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 506 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::cpuHandle.
static void HAL_enablePwm (HAL_Handle handle) inline static
Enables the PWM devices.
Turns on the outputs of the EPWM peripheral which will allow the power switches to be controlled.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 275 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
void HAL_enablePwmInt (HAL_Handle handle)
Enables the PWM interrupt.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 517 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::cpuHandle, _HAL_Obj_::pieHandle, and _HAL_Obj_::pwmHandle.
static ADC_SocSampleDelay_e HAL_getAdcSocSampleDelay (HAL_Handle handle, const ADC_SocNumber_e socNumber) inline static
Gets the ADC delay value.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] socNumber The ADC SOC number
Returns
The ADC delay value
Definition at line 296 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::adcHandle.
static _iq HAL_getBias (HAL_Handle handle, const HAL_SensorType_e sensorType, uint_least8_t sensorNumber) inline static
Gets the ADC bias value.
The ADC bias contains the feedback circuit's offset and bias. Bias is the mathematical offset used when a bi-polar signal is read into a uni-polar ADC.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
Returns
The ADC bias value
Definition at line 313 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ, _HAL_Obj_::adcBias, HAL_SensorType_Current, HAL_SensorType_Voltage, _HAL_AdcData_t_::I, _HAL_AdcData_t_::V, and _MATH_vec3_::value.
Referenced by HAL_updateAdcBias().
static _iq HAL_getCurrentScaleFactor (HAL_Handle handle) inline static
Gets the current scale factor.
The current scale factor is defined as USER_ADC_FULL_SCALE_CURRENT_A/USER_IQ_FULL_SCALE_CURRENT_A. This scale factor is not used when converting between PU amps and real amps.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Returns
The current scale factor
Definition at line 340 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::current_sf.
Referenced by HAL_readAdcData(), and HAL_readAdcDataWithOffsets().
static uint_least8_t HAL_getNumCurrentSensors (HAL_Handle handle) inline static
Gets the number of current sensors.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Returns
The number of current sensors
Definition at line 351 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::numCurrentSensors.
Referenced by HAL_setParams(), and HAL_updateAdcBias().
static uint_least8_t HAL_getNumVoltageSensors (HAL_Handle handle) inline static
Gets the number of voltage sensors.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Returns
The number of voltage sensors
Definition at line 363 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::numVoltageSensors.
Referenced by HAL_setParams(), and HAL_updateAdcBias().
static _iq HAL_getOffsetBeta_lp_pu (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber) inline static
Gets the value used to set the low pass filter pole for offset estimation.
An IIR single pole low pass filter is used to find the feedback circuit's offsets. This function returns the value of that pole.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
Returns
The value used to set the low pass filter pole, pu
Definition at line 379 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ, HAL_SensorType_Current, HAL_SensorType_Voltage, OFFSET_getBeta(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
static _iq HAL_getOffsetValue (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber) inline static
Gets the offset value.
The offsets that are calculated during the feedback circuits calibrations are returned from the IIR filter object.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
Returns
The offset value
Definition at line 407 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ, HAL_SensorType_Current, HAL_SensorType_Voltage, OFFSET_getOffset(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
uint16_t HAL_getOscTrimValue (int16_t coarse, int16_t fine)
Converts coarse and fine oscillator trim values into a single 16bit word value.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] coarse The coarse trim portion of the oscillator trim
[in] fine The fine trim portion of the oscillator trim
Returns
The combined trim value
Definition at line 220 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
Referenced by HAL_osc1Comp(), and HAL_osc2Comp().
static uint32_t HAL_getTimerPeriod (HAL_Handle handle, const uint_least8_t timerNumber) inline static
Gets the timer period.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
Returns
The timer period
Definition at line 666 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static _iq HAL_getVoltageScaleFactor (HAL_Handle handle) inline static
Gets the voltage scale factor.
The voltage scale factor is defined as USER_ADC_FULL_SCALE_VOLTAGE_V/USER_IQ_FULL_SCALE_VOLTAGE_V. This scale factor is not used when converting between PU volts and real volts.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Returns
The voltage scale factor
Definition at line 435 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::voltage_sf.
Referenced by HAL_readAdcData(), and HAL_readAdcDataWithOffsets().
HAL_Handle HAL_init (void * pMemory, const size_t numBytes)
Initializes the hardware abstraction layer (HAL) object.
Initializes all handles to the microcontroller peripherals. Returns a handle to the HAL object.
Parameters
[in] pMemory A pointer to the memory for the hardware abstraction layer object
[in] numBytes The number of bytes allocated for the hardware abstraction layer object, bytes
Returns
The hardware abstraction layer (HAL) object handle
Definition at line 566 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle, _HAL_Obj_::afeHandle, _HAL_Obj_::clkHandle, _HAL_Obj_::cpuHandle, _HAL_Obj_::flashHandle, _HAL_Obj_::gpioHandle, HAL_disableWdog(), _HAL_Obj_::offset_I, OFFSET_init(), _HAL_Obj_::offset_V, _HAL_Obj_::offsetHandle_I, _HAL_Obj_::offsetHandle_V, _HAL_Obj_::oscHandle, _HAL_Obj_::pieHandle, _HAL_Obj_::pllHandle, _HAL_Obj_::pwmDacHandle, _HAL_Obj_::pwmHandle, _HAL_Obj_::pwrHandle, _HAL_Obj_::timerHandle, and _HAL_Obj_::wdogHandle.
static void HAL_initIntVectorTable (HAL_Handle handle) inline static
Initializes the interrupt vector table.
Points the ISR to the function mainISR.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 464 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References mainISR(), and _HAL_Obj_::pieHandle.
void HAL_osc1Comp (HAL_Handle handle, const int16_t sensorSample)
Executes the oscillator 1 calibration based on input sample.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 166 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References FP_ROUND, FP_SCALE, getOsc1CoarseTrim, getOsc1FineTrimOffset, getOsc1FineTrimSlope, getRefTempOffset, HAL_getOscTrimValue(), OSC_POSTRIM, OSC_POSTRIM_OFF, and _HAL_Obj_::oscHandle.
Referenced by HAL_OscTempComp().
void HAL_osc2Comp (HAL_Handle handle, const int16_t sensorSample)
Executes the oscillator 2 calibration based on input sample.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 193 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References FP_ROUND, FP_SCALE, getOsc2CoarseTrim, getOsc2FineTrimOffset, getOsc2FineTrimSlope, getRefTempOffset, HAL_getOscTrimValue(), OSC_POSTRIM, OSC_POSTRIM_OFF, and _HAL_Obj_::oscHandle.
Referenced by HAL_OscTempComp().
void HAL_OscTempComp (HAL_Handle handle)
Executes the oscillator 1 and 2 calibration functions.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 100 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle, HAL_osc1Comp(), and HAL_osc2Comp().
Referenced by HAL_cal().
static void HAL_readAdcData (HAL_Handle handle, HAL_AdcData_t * pAdcData) inline static
Reads the ADC data.
Reads in the ADC result registers, adjusts for offsets, and scales the values according to the settings in user.h. The structure gAdcData holds three phase voltages, three line currents, and one DC bus voltage.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pAdcData A pointer to the ADC data buffer
Definition at line 487 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ12mpy, _HAL_Obj_::adcBias, _HAL_Obj_::adcHandle, _HAL_AdcData_t_::dcBus, HAL_getCurrentScaleFactor(), HAL_getVoltageScaleFactor(), _HAL_AdcData_t_::I, _HAL_AdcData_t_::V, and _MATH_vec3_::value.
static void HAL_readAdcDataWithOffsets (HAL_Handle handle, HAL_AdcData_t * pAdcData) inline static
Reads the ADC data.
Reads in the ADC result registers, and scales the values according to the settings in user.h. The structure gAdcData holds three phase voltages, three line currents, and one DC bus voltage.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pAdcData A pointer to the ADC data buffer
Definition at line 543 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ12mpy, _HAL_Obj_::adcHandle, _HAL_AdcData_t_::dcBus, HAL_getCurrentScaleFactor(), HAL_getVoltageScaleFactor(), _HAL_AdcData_t_::I, _HAL_AdcData_t_::V, and _MATH_vec3_::value.
static uint16_t HAL_readPwmCmpA (HAL_Handle handle, const PWM_Number_e pwmNumber) inline static
Reads PWM compare register A.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pwmNumber The PWM number
Returns
The PWM compare value
Definition at line 1073 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
static uint16_t HAL_readPwmCmpAM (HAL_Handle handle, const PWM_Number_e pwmNumber) inline static
Reads PWM compare mirror register A.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pwmNumber The PWM number
Returns
The PWM compare value
Definition at line 1090 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
static uint16_t HAL_readPwmCmpB (HAL_Handle handle, const PWM_Number_e pwmNumber) inline static
Reads PWM compare register B.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pwmNumber The PWM number
Returns
The PWM compare value
Definition at line 1107 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
static uint16_t HAL_readPwmPeriod (HAL_Handle handle, const PWM_Number_e pwmNumber) inline static
Reads PWM period register.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pwmNumber The PWM number
Returns
The PWM period value
Definition at line 1227 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::pwmHandle.
static uint32_t HAL_readTimerCnt (HAL_Handle handle, const uint_least8_t timerNumber) inline static
Reads the timer count.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
Returns
The timer count
Definition at line 596 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static void HAL_reloadTimer (HAL_Handle handle, const uint_least8_t timerNumber) inline static
Reloads the timer.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
Definition at line 608 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static void HAL_setAdcSocSampleDelay (HAL_Handle handle, const ADC_SocNumber_e socNumber, const ADC_SocSampleDelay_e sampleDelay) inline static
Sets the ADC SOC sample delay value.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] socNumber The SOC number
[in] sampleDelay The delay value for the ADC
Definition at line 680 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::adcHandle.
static void HAL_setBias (HAL_Handle handle, const HAL_SensorType_e sensorType, uint_least8_t sensorNumber, const _iq bias) inline static
Sets the ADC bias value.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
[in] bias The ADC bias value
Definition at line 697 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::adcBias, HAL_SensorType_Current, HAL_SensorType_Voltage, _HAL_AdcData_t_::I, _HAL_AdcData_t_::V, and _MATH_vec3_::value.
Referenced by HAL_setParams(), and HAL_updateAdcBias().
static void HAL_setCurrentScaleFactor (HAL_Handle handle, const _iq current_sf) inline static
Sets the current scale factor in the hardware abstraction layer.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] current_sf The current scale factor
Definition at line 772 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::current_sf.
Referenced by HAL_setParams().
static void HAL_setGpioHigh (HAL_Handle handle, const GPIO_Number_e gpioNumber) inline static
Sets the GPIO pin high.
Takes in the enumeration GPIO_Number_e and sets that GPIO pin high.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] gpioNumber The GPIO number
Definition at line 723 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::gpioHandle.
static void HAL_setGpioLow (HAL_Handle handle, const GPIO_Number_e gpioNumber) inline static
Sets the GPIO pin low.
Takes in the enumeration GPIO_Number_e and clears that GPIO pin low.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] gpioNumber The GPIO number
Definition at line 757 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::gpioHandle.
static void HAL_setNumCurrentSensors (HAL_Handle handle, const uint_least8_t numCurrentSensors) inline static
Sets the number of current sensors.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] numCurrentSensors The number of current sensors
Definition at line 786 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::numCurrentSensors.
Referenced by HAL_setParams().
static void HAL_setNumVoltageSensors (HAL_Handle handle, const uint_least8_t numVoltageSensors) inline static
Sets the number of voltage sensors.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] numVoltageSensors The number of voltage sensors
Definition at line 800 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::numVoltageSensors.
Referenced by HAL_setParams().
static void HAL_setOffsetBeta_lp_pu (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq beta_lp_pu) inline static
Sets the value used to set the low pass filter pole for offset estimation.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
[in] beta_lp_pu The value used to set the low pass filter pole, pu
Definition at line 816 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References HAL_SensorType_Current, HAL_SensorType_Voltage, OFFSET_setBeta(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
Referenced by HAL_setParams().
static void HAL_setOffsetInitCond (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq initCond) inline static
Sets the offset initial condition value for offset estimation.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
[in] initCond The initial condition value
Definition at line 841 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References HAL_SensorType_Current, HAL_SensorType_Voltage, OFFSET_setInitCond(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
Referenced by HAL_setParams().
static void HAL_setOffsetValue (HAL_Handle handle, const HAL_SensorType_e sensorType, const uint_least8_t sensorNumber, const _iq value) inline static
Sets the initial offset value for offset estimation.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] sensorType The sensor type
[in] sensorNumber The sensor number
[in] value The initial offset value
Definition at line 866 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References HAL_SensorType_Current, HAL_SensorType_Voltage, OFFSET_setOffset(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
Referenced by HAL_setParams().
void HAL_setParams (HAL_Handle handle, const USER_Params * pUserParams)
Sets the hardware abstraction layer parameters.
Sets up the microcontroller peripherals. Creates all of the scale factors for the ADC voltage and current conversions. Sets the initial offset values for voltage and current measurements.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pUserParams The pointer to the user parameters
Definition at line 688 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _IQ, _IQ12mpy, _HAL_Obj_::cpuHandle, _USER_Params_::ctrlFreq_Hz, _USER_Params_::current_sf, HAL_cal(), HAL_getNumCurrentSensors(), HAL_getNumVoltageSensors(), HAL_Qep_QEP1, HAL_SensorType_Current, HAL_SensorType_Voltage, HAL_setBias(), HAL_setCurrentScaleFactor(), HAL_setNumCurrentSensors(), HAL_setNumVoltageSensors(), HAL_setOffsetBeta_lp_pu(), HAL_setOffsetInitCond(), HAL_setOffsetValue(), HAL_setupAdcs(), HAL_setupAfe(), HAL_setupClks(), HAL_setupFlash(), HAL_setupGpios(), HAL_setupPeripheralClks(), HAL_setupPie(), HAL_setupPll(), HAL_setupPwmDacs(), HAL_setupPwms(), HAL_setupQEP(), HAL_setupTimers(), HAL_setVoltageScaleFactor(), _USER_Params_::numCurrentSensors, _USER_Params_::numVoltageSensors, _USER_Params_::offsetPole_rps, _USER_Params_::pwmPeriod_usec, _USER_Params_::systemFreq_MHz, and _USER_Params_::voltage_sf.
static void HAL_setTimerPeriod (HAL_Handle handle, const uint_least8_t timerNumber, const uint32_t period) inline static
Sets the timer period.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
[in] period The timer period
Definition at line 651 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static void HAL_setTrigger (HAL_Handle handle, const SVGENCURRENT_IgnoreShunt_e ignoreShunt, const int16_t minwidth, const int16_t cmpOffset) inline static
Definition at line 1120 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References ignore_a, ignore_ab, ignore_ac, ignore_b, ignore_c, _HAL_Obj_::pwmHandle, and use_all.
void HAL_setupAdcs (HAL_Handle handle)
Sets up the ADCs (Analog to Digital Converters)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 883 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::adcHandle.
Referenced by HAL_setParams().
void HAL_setupAfe (HAL_Handle halHandle)
Sets up the AFE (Analog Front End)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 826 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::afeHandle.
Referenced by HAL_setParams().
void HAL_setupClks (HAL_Handle handle)
Sets up the clocks.
Sets up the micro-controller's main oscillator
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 964 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::clkHandle.
Referenced by HAL_setParams().
void HAL_setupFaults (HAL_Handle handle)
Configures the fault protection logic.
Sets up the trip zone inputs so that when a comparator signal from outside the micro-controller trips a fault, the EPWM peripheral blocks will force the power switches into a high impedance state.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 536 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::gpioHandle, and _HAL_Obj_::pwmHandle.
void HAL_setupFlash (HAL_Handle handle)
Sets up the FLASH.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 994 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::flashHandle.
Referenced by HAL_setParams().
void HAL_setupGpios (HAL_Handle handle)
Sets up the GPIO (General Purpose I/O) pins.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 1015 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::gpioHandle.
Referenced by HAL_setParams().
void HAL_setupPeripheralClks (HAL_Handle handle)
Sets up the peripheral clocks.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 1192 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::clkHandle.
Referenced by HAL_setParams().
void HAL_setupPie (HAL_Handle handle)
Sets up the PIE (Peripheral Interrupt Expansion)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 1171 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::pieHandle.
Referenced by HAL_setParams().
void HAL_setupPll (HAL_Handle handle, const PLL_ClkFreq_e clkFreq)
Sets up the PLL (Phase Lock Loop)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] clkFreq The clock frequency
Definition at line 1229 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::pllHandle.
Referenced by HAL_setParams().
void HAL_setupPwmDacs (HAL_Handle handle)
Sets up the PWM DACs (Pulse Width Modulator Digital to Analof Converters)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 1444 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::pwmDacHandle.
Referenced by HAL_setParams().
void HAL_setupPwms (HAL_Handle handle, const float_t systemFreq_MHz, const float_t pwmPeriod_usec, const uint_least16_t numPwmTicksPerIsrTick)
Sets up the PWMs (Pulse Width Modulators)
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] systemFreq_MHz The system frequency, MHz
[in] pwmPeriod_usec The PWM period, usec
[in] numPwmTicksPerIsrTick The number of PWM clock ticks per ISR clock tick
Definition at line 1278 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::clkHandle, HAL_PWM_DBFED_CNT, HAL_PWM_DBRED_CNT, and _HAL_Obj_::pwmHandle.
Referenced by HAL_setParams().
void HAL_setupQEP (HAL_Handle handle, HAL_QepSelect_e qep)
Sets up the QEP peripheral.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Referenced by HAL_setParams().
void HAL_setupTimers (HAL_Handle handle, const float_t systemFreq_MHz)
Sets up the timers.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] systemFreq_MHz The system frequency, MHz
Definition at line 1517 of file drv8301kit_revD/f28x/f2805x/src/hal.c.
References _HAL_Obj_::timerHandle.
Referenced by HAL_setParams().
static void HAL_setVoltageScaleFactor (HAL_Handle handle, const _iq voltage_sf) inline static
Sets the voltage scale factor in the hardware abstraction layer.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] voltage_sf The voltage scale factor
Definition at line 889 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::voltage_sf.
Referenced by HAL_setParams().
static void HAL_startTimer (HAL_Handle handle, const uint_least8_t timerNumber) inline static
Starts the timer.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
Definition at line 622 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static void HAL_stopTimer (HAL_Handle handle, const uint_least8_t timerNumber) inline static
Stops the timer.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] timerNumber The timer number, 0,1 or 2
Definition at line 636 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::timerHandle.
static void HAL_toggleGpio (HAL_Handle handle, const GPIO_Number_e gpioNumber) inline static
Toggles the GPIO pin.
Takes in the enumeration GPIO_Number_e and toggles that GPIO pin.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] gpioNumber The GPIO number
Definition at line 740 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _HAL_Obj_::gpioHandle.
static void HAL_updateAdcBias (HAL_Handle handle) inline static
Updates the ADC bias values.
This function is called before the motor is started. It sets the voltage and current measurement offsets.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
Definition at line 981 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References HAL_getBias(), HAL_getNumCurrentSensors(), HAL_getNumVoltageSensors(), HAL_SensorType_Current, HAL_SensorType_Voltage, HAL_setBias(), OFFSET_getOffset(), _HAL_Obj_::offsetHandle_I, and _HAL_Obj_::offsetHandle_V.
static void HAL_writeDacData (HAL_Handle handle, HAL_DacData_t * pDacData) inline static
Writes DAC data to the PWM comparators for DAC (digital-to-analog conversion) output.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pDacData The pointer to the DAC data
Definition at line 1016 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQtoIQ15, _HAL_Obj_::pwmDacHandle, and _HAL_DacData_t_::value.
static void HAL_writePwmData (HAL_Handle handle, HAL_PwmData_t * pPwmData) inline static
Writes PWM data to the PWM comparators for motor control.
Parameters
[in] handle The hardware abstraction layer (HAL) handle
[in] pPwmData The pointer to the PWM data
Definition at line 1039 of file drv8301kit_revD/f28x/f2805x/src/hal.h.
References _IQ, _IQmpy, _IQsat, _HAL_Obj_::pwmHandle, _HAL_PwmData_t_::Tabc, and _MATH_vec3_::value.
interrupt void mainISR (void)
Referenced by HAL_initIntVectorTable().